# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
random_tensor = torch.rand(7,7)
random_tensor, random_tensor.shape

# Create random tensor


(tensor([[0.3095, 0.3228, 0.4352, 0.2327, 0.1102, 0.9124, 0.0581],
         [0.7443, 0.2701, 0.1910, 0.9417, 0.8579, 0.3712, 0.9733],
         [0.5072, 0.1041, 0.6078, 0.9034, 0.9917, 0.8431, 0.7459],
         [0.4868, 0.1726, 0.4618, 0.7712, 0.4687, 0.7439, 0.3302],
         [0.5066, 0.9359, 0.0995, 0.7471, 0.0641, 0.4234, 0.6179],
         [0.7678, 0.0196, 0.3946, 0.5080, 0.3451, 0.9837, 0.6843],
         [0.1152, 0.2531, 0.2241, 0.7972, 0.4298, 0.1922, 0.8697]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
random_tensor2 = torch.rand(1,7)
resultant_tensor = torch.matmul(random_tensor,random_tensor2.T) # transposing tensor2 (for multiplication)
resultant_tensor
# Perform matrix multiplication


tensor([[1.3070],
        [2.4385],
        [2.5963],
        [1.9327],
        [1.8658],
        [1.9895],
        [1.4659]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
random_tensorA = torch.rand(7,7)
random_tensorB = torch.rand(1,7)
# Matrix multiply tensors

result = torch.matmul(random_tensorA,random_tensorB.T)
result


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [41]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

# Create two random tensors
random_tensorA = torch.rand(7,7)
random_tensorB = torch.rand(1,7)
# Matrix multiply tensors

result = torch.matmul(random_tensorA,random_tensorB.T)
result


tensor([[1.0144],
        [0.6537],
        [1.3518],
        [1.4114],
        [0.6833],
        [1.3447],
        [1.0703]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [44]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device:{device}")
# Create two random tensors on GPU
tensor1 = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)

tensor1,tensor2

Device:cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [47]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(tensor1,tensor2.T)
output

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [48]:
# Find max
max = torch.max(output)
# Find min
min = torch.min(output)

max,min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [50]:
# Find arg max
maxIndex = torch.argmax(output)

# Find arg min
minIndex = torch.argmin(output)

maxIndex,minIndex

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [56]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorA = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensorB = torch.squeeze(tensorA)

# Print out tensors and their shapes
tensorA,tensorA.shape,tensorB,tensorB.shape



(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))