## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__);

2.1.0+cu121


 # Introduction to Tensors

 ### Creating  tensors

PyTorch Tensors are Created using torch.tensor();

# SCALAR

In [ ]:
# Scalar

scalar = torch.tensor(7);
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
scalar.shape

torch.Size([])

# VECTOR

In [ ]:
# Vector
vector = torch.tensor([7,7]);
vector

tensor([7, 7])

In [ ]:
# Vector dimensions
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

 # MATRIX

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,9],[8,9]]);
MATRIX

tensor([[7, 9],
        [8, 9]])

In [ ]:
#dimensions
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([8, 9])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

# TENSOR


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[54,64,23],[12,56,23]]]);
TENSOR

tensor([[[ 1,  2,  3],
         [54, 64, 23],
         [12, 56, 23]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape
### 1 Dimenstion of 3 by 3

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [54, 64, 23],
        [12, 56, 23]])

# Random tensors

why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those randonumbers to better represent data.

`Start with random numbers ->  look at data -> update random numbrs -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,4);
random_tensor

tensor([[[0.7367, 0.7108, 0.7158, 0.3675],
         [0.0981, 0.8049, 0.9221, 0.5545],
         [0.6945, 0.7899, 0.0525, 0.6724]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels, height, width,
random_image_size_tensor

tensor([[[5.6003e-01, 3.7933e-01, 8.6808e-04,  ..., 5.6144e-01,
          2.0524e-01, 1.5212e-01],
         [5.1389e-01, 9.1142e-01, 9.6816e-01,  ..., 4.1698e-01,
          6.5180e-01, 2.8672e-01],
         [6.6139e-01, 9.4796e-01, 2.3274e-01,  ..., 2.7344e-01,
          8.8968e-01, 1.2622e-01],
         ...,
         [7.9678e-02, 5.9804e-01, 4.5697e-01,  ..., 5.9161e-01,
          1.3625e-01, 2.8994e-01],
         [6.2492e-01, 4.3300e-01, 7.7798e-01,  ..., 6.8790e-01,
          2.2410e-01, 2.7952e-01],
         [9.0658e-02, 5.7535e-01, 6.6216e-01,  ..., 8.8973e-01,
          7.8857e-01, 8.1795e-01]],

        [[5.7989e-03, 3.7881e-01, 8.3967e-02,  ..., 2.5088e-01,
          3.7460e-01, 3.3624e-01],
         [7.9479e-01, 4.7588e-01, 3.6038e-01,  ..., 5.5459e-01,
          4.5587e-01, 5.2778e-01],
         [9.0998e-01, 7.1819e-01, 4.2390e-01,  ..., 3.5933e-01,
          1.7797e-01, 9.0572e-01],
         ...,
         [1.0692e-01, 9.0050e-01, 7.5404e-01,  ..., 4.3039e-01,
          2.937

# ZEROS AND ONES

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# default datatype of tensor
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1,end=1000,step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
# Creting tensors like (create tensors of same length/like of other tensors)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big errors you will run into with PyTorch  and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor (default)
float_32_tensor = torch.tensor([3.0,6.0,9.0 ])
float_32_tensor.dtype

torch.float32

In [ ]:
# Other data types
float_16_tensor = torch.tensor([3.0,6.0,9.0 ],
                               dtype=torch.float16,
                               device=None, #"cpu" -> default : specifies what device your tensor is on
                               requires_grad=False); # whether or not to track gradients with tensor operations

float_16_tensor.dtype

torch.float16

In [ ]:
# datatype conversion
new_float_16_tensor = float_32_tensor.type(torch.float16)
new_float_16_tensor
new_float_16_tensor = float_32_tensor.type(torch.long);
new_float_16_tensor.dtype

torch.int64

In [ ]:
float_32_tensor * float_16_tensor ## Dies not throws error


tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor * new_float_16_tensor


tensor([ 9., 36., 81.])

## Getting information from tensors

### Getting information from tensors  :: tensor attributes

1. Tensors not rigt datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,5);
some_tensor

tensor([[0.7805, 0.2185, 0.4579, 0.2569, 0.2661],
        [0.3034, 0.0662, 0.1529, 0.9467, 0.7036],
        [0.6729, 0.5532, 0.9292, 0.4387, 0.7274]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"device tensor is on : {some_tensor.device}")

tensor([[0.7805, 0.2185, 0.4579, 0.2569, 0.2661],
        [0.3034, 0.0662, 0.1529, 0.9467, 0.7036],
        [0.6729, 0.5532, 0.9292, 0.4387, 0.7274]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 5])
device tensor is on : cpu


## Manipulating Tensors (tensor Operators)

Tensor operations include :    
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix_multiplication

In [ ]:
# Create a tensor and add 109 to it
tensor = torch.tensor([1,2,3])
tensor + 109


tensor([110, 111, 112])

In [ ]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([100, 200, 300])

In [ ]:
# Subtract 100
tensor = tensor - 100
tensor


tensor([-10,  90, 190])

In [ ]:
# Try out PyTorch in-build functions
torch.mul(tensor,10)


tensor([-100,  900, 1900])

In [ ]:
torch.add(tensor,10)

tensor([  0, 100, 200])

### Matrix multiplications

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix Multiplication (dot product)

There are two main rules while performing matrix multiplication needs to satisfy:
1. The **Inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,5) @ (5,2)` will work

@ - can also be used to matrix multiplication  but prefer using torch.matmul()

2. The resulting matrix has the shape of the **Outer dimensions**
*`(2,3) @ (3,2)` -> `(2,2)`
*`(3,1) @ (1,3)` -> `(3,3)`

In [ ]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([-10,  90, 190]) * tensor([-10,  90, 190])
Equals: tensor([  100,  8100, 36100])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(44300)

In [ ]:
## More complex matrix multipliation
tensor1 = torch.rand(5,5)
tensor2 = torch.rand(5,3)
torch.matmul(tensor1,tensor2)

tensor([[0.5592, 0.7677, 0.4675],
        [1.2804, 1.5998, 0.8927],
        [0.8423, 1.4300, 0.8132],
        [0.9963, 1.5530, 1.0128],
        [1.0080, 1.5643, 1.0466]])

### One of the most common error in deep learning are shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B)  # torch.mm is the same as torch.matmul (its an alias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

1. To fix our tensor shape issues,we can manipulate the shape of one of our tensors using transpose.

**Transpose** switches the axes or dimensions of a given translator

In [ ]:
# Transposing tensor B (tensor.T)

tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
## The matrix multiplication operation works when tensor_B is transposed
print(f"original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")


output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"outpu shape : {output.shape}")

original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
outpu shape : torch.Size([3, 3])


### Tensor Aggregation (finding min,max,mean,sum etc)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the Avg or mean
torch.mean(x) ## gives error , needs to be complex dtype or float dtytpe

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# Find mean - Note : the torch.mean() fucntion requires a tensor of float32 dytype
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
## Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max (index)

In [ ]:
# find the position/index in tensor that has a minimum value
x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
#finding max value index
x.argmax(),torch.argmax(x)

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1.0,11.0)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Change the view
z = x.view(1,10)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5 # change first element of z (view)
z,x  # x will also change

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1) # default dimension 0
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# Squeeze (torch.squeeze()   --> removes all single dimensions from tensor)
x = torch.zeros(2,1,2,1,2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
#Squeeze
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
# Unsqueeze (torch.unsqueeze() --> adds a single dimension to a target dimension at a specific dim)
x = torch.tensor([1,2,3,4])
torch.unsqueeze(x,0)

tensor([[1, 2, 3, 4]])

In [ ]:
torch.unsqueeze(x,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
# torch.permute --> rearranges the dimensions of a target tensor in a specified order
x = torch.rand(size=(224,224,3)) # [height, widht and color chaneels]
print(f"x_size :{x.size()}")

# permute the original tensor to rearrange the axis or dim order
x_permuted = x.permute(2,0,1) ## Shifts axis 0 to 1, 1 to 2 and 2 to 0
print(f"permuted :{x_permuted.shape}")  #[color_channels,height,width]


x_size :torch.Size([224, 224, 3])
permuted :torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with pyTorch is similiar to indexing with Numpy

In [ ]:
## Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on the most inner bracket (dim = 2)
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ": " to select "all" of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only 1 index values of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensor and Numpy

Numpy is a popular scientific python numerical computing library
And because of this, pyTorch has functionality to interact with it.

* Data in Numpy, want in pyTorch -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

# Warning when converting numpy to pytorch , pytorch reflects numpy's default datatype of float64 unless specified

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor_float32 = torch.from_numpy(array).type(torch.float32)
array,tensor,tensor_float32

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array,tensor # Does not affects tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()  ## Takes tensor's default dtype = float32
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor # numpy_tensor does not gets affected

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# PyTorch Reproducibility (trying to take random out of random )

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of data -> again -> again -> again..`

To Reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7020, 0.8865, 0.7904, 0.8395],
        [0.0424, 0.4200, 0.1287, 0.5557],
        [0.3070, 0.4893, 0.7660, 0.5523]])
tensor([[0.3919, 0.5687, 0.4152, 0.0359],
        [0.3332, 0.1615, 0.2415, 0.7696],
        [0.5412, 0.8161, 0.2461, 0.5124]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
## Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42  ## Any value (Different flavor of randomness)

torch.manual_seed(RANDOM_SEED)  ## Set random seed for next block
random_tensor_C = torch.rand(3,4)  ## tensor generated based on random seed

torch.manual_seed(RANDOM_SEED)  ## Set random seed for next block
random_tensor_D = torch.rand(3,4) ## tensor generated based on random seed

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D) # equal


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on GPU's (making faster computations)



### 1. Getting a GPU

1. Easiest - Use Google Collab for a free GPU (options to upgrade as well )
2. Use your own GPU
3. USe Cloud computing - GCP, AWS, Azure


For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup Documentation



In [ ]:
# change runtime and choose a GPU

# GPU specifications
!nvidia-smi

Tue Jan  9 13:03:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available() # cuda is nvidia's programming interface that allows us to use GPUs for computing


True

In [ ]:
# Set up device agnostic code ::: run on GPU if exists if not use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

GPU results in faster computations

In [ ]:
# Create a tensor (default is on the cpu)
tensor = torch.tensor([1,2,3]) # default on cpu

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)  # device = "cuda" if GPU is available (device agnostic code)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the CPU

In [ ]:
## If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix GPU tensor with Numpy issue , we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [16]:
 tensor_on_gpu # remains unchanged


tensor([1, 2, 3], device='cuda:0')